forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/apt', '2.2.1'
mod 'puppetlabs/stdlib', '4.10.0'
mod 'puppet/unattended_upgrades', '1.0.3'

mod 'guest_additions',
  :git => 'git://github.com/pcfens/puppet-guest_additions'

# sudo
mod 'saz/sudo', '3.1.0'
